# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Scarecrow"
license = "MPL-2.0"
licenselink = "https://github.com/strootje/scarecrow/blob/master/LICENSE.md"
description = ""
homepage = "http://strootje.com/project/scarecrow/"
tags = ["blog", "portfolio"]
features = ["blog"]
min_version = "0.25.0"

[author]
  name = "Bas Stroosnijder"
  homepage = "http://strootje.com"
