title: Scarecrow
baseURL: https://strootje.github.com/
paginate: 3

defaultContentLanguage: en
languages:
  en:
    languageName: English
    contentDir: content/en

params:
  Author:
    Username: Strootje
    Lastname: Stroosnijder
    Firstname: Bastiaan
    Gender: male
    LogoSrc: https://placekitten.com/g/180/180
    LogoAlt: testing
    Tagline: ":bike: this is my tagline"
  Social:
    github: strootje
    itchio: strootje
    linkedin: bas-stroosnijder
    instagram: strootje
    rss: posts
