languageCode: "en"

title: "Scarecrow"
baseURL: "https://strootje.github.io/hugo-scarecrow-theme"
paginate: 6

params:
  author:
    username: "strootje"
    lastname: "Stroosnijder"
    firstname: "Bastiaan"
    gender: "male"
  social:
    show-follow: true
    show-share: true
    accounts:
      github: "???"
      linkedin: "???"
      rss: "posts"
  # ackee:
  #   server: https://analytics.strootje.com
  #   domainId: 123132123

menu:
  pages:
  - name: "About"
  - name: "Contact"
  legal:
  - name: "Privacy"
  - name: "Terms of Use"
  powered:
  - name: hugo
    title: Hugo
    url: https://gohugo.io/
    target: _blank
  - name: scarecrow
    title: Scarecrow
    url: https://strootje.github.io/hugo-scarecrow-theme
    target: _blank
