languageCode: "en"

title: "Scarecrow"
baseURL: "https://strootje.github.io/hugo-scarecrow-theme"
paginate: 9

params:
  # theme:
  #   colors:
  #     faded: '#333'
  #     primary: '#405F7F'
  #     secondary: '#C4BD5B'
  #     tertiary: '#B4536A'
  author:
    username: "strootje"
    lastname: "Stroosnijder"
    firstname: "Bastiaan"
    gender: "male"
    tagline: "some awesome shit here"
    # logo: "images/noimage.jpg" #resource
    # logo: "https://placekitten.com/g/200/200" #href
    # logo: "bas@strootje.com" #gravatar
    logoalt: "testing"
  social:
    # show-follow: true
    # show-share: true
    accounts:
      github: "???"
      linkedin: "???"
      instagram: "???"
      rss: "posts"
  # ackee:
  #   server: https://analytics.strootje.com
  #   domainId: 123132123

languages:
  en:
    languageName: English
  nl:
    languageName: Dutch

menu:
  pages:
  - name: About
    url: /about
  - name: Contact
  legal:
  - name: Privacy
  - name: "Terms of Use"
  # powered:
  # - name: hugo
  #   title: Hugo
  #   url: https://gohugo.io/
  # - name: scarecrow
  #   title: Scarecrow
  #   url: https://strootje.github.io/hugo-scarecrow-theme
