title: Scarecrow
baseURL: https://strootje.github.com/
paginate: 9

params:
  Author:
    Username: Strootje
    Lastname: Stroosnijder
    Firstname: Bastiaan
    Gender: male
    Logo: https://placekitten.com/g/180/180
    LogoAlt: testing
  Social:
    github: strootje
    linkedin: bas-stroosnijder
    instagram: strootje
    rss: posts
