languageCode = "en"

title = "scarecrow"
baseURL = "http://localhost:1313/"
DefaultContentLanguage = "en"
paginate = 6

[languages.en]
languageName = "English"
contentDir = "content/en"
weight = 1

[languages.nl]
languageName = "Nederlands"
contentDir = "content/nl"
weight = 2

[params]
	author = "Scarecrow"
	logo = "images/scarecrow.jpg"
	font = "Poppins"
	showRelated = true
	showHeaders = false
	[params.menu.social]
		target = "blank"
	[params.about]
		title = "Bas Stroosnijder"
		tagline = "FOSS since 1991"
		[params.about.logo]
			src = "images/scarecrow.jpg"

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1
[[menu.main]]
	name = "About"
	url = "/about"
	weight = 2
[[menu.main]]
	name = "Contact"
	url = "/contact"
	weight = 3

[[menu.social]]
	name = "Linkedin"
	url = "https://linkedin.com/"
	pre = "fab fa-fw fa-lg fa-linkedin"
	weight = 1
[[menu.social]]
	name = "Github"
	url = "https://github.com/"
	pre = "fab fa-fw fa-lg fa-github"
	weight = 2

[[menu.legal]]
	name = "Privacy"
	url = "/privacy"
	weight = 1
