languageCode = "en"

title = "scarecrow"
baseURL = "https://www.strootje.com/hugo-scarecrow-theme"
paginate = 6

enableEmoji = true
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsOptions = "linenos=true"

# googleAnalytics = "UA-123-45"
[privacy.googleAnalytics]
	respectDoNotTrack = true


[languages.en]
	languageName = "English"
	contentDir = "content/en"
	weight = 1

[params]
	callToAction = "/contact"
[params.options]
	showCallToAction = true
	showFollow = true
	showRelated = true
	showShare = true
[params.author]
	name = "Someone Awesome"
	tagline = "asdasd kjashdlkjad"
	logo = "images/scarecrow.jpg"
[params.social]
	github = "???"
	instagram = "???"
	linkedin = "???"
	rss = "posts"
	stackoverflow = "???"

[[menu.main]]
	name = "About"
	weight = 100
	title = "about"
	url = "/about"
[[menu.main]]
	name = "Contact"
	weight = 200
	title = "contact"
	url = "/contact"
