languageCode = "en-us"

title = "scarecrow"
baseURL = "http://localhost/"
DefaultContentLanguage = "en"
paginate = 6

[languages.en]
languageName = "English"
weight = 1

[params]
	author = "Scarecrow"
	logo = "images/scarecrow.jpg"
	font = "Poppins"
	showRelated = true
	showHeaders = false
	[params.about]
		title = "Bas Stroosnijder"
		tagline = "FOSS since 1991"
		[params.about.logo]
			src = "images/scarecrow.jpg"
	[[params.poweredBy]]
		title = "Hugo"
		url = "https://gohugo.io"
	[[params.poweredBy]]
		title = "Scarecrow"
		url = "https://strootje.com/projs/scarecrow"

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1
[[menu.main]]
	name = "About"
	url = "/about/"
	weight = 2
[[menu.main]]
	name = "Contact"
	url = "/contact/"
	weight = 3
