languageCode = "en-us"

title = "scarecrow"

[params]
	author = "Scarecrow"
	logo = "/images/logo.jpg"
	font = "Poppins"
	showRelated = true
	showHeaders = false
	[[params.poweredBy]]
		title = "Hugo"
		url = "https://gohugo.io"
	[[params.poweredBy]]
		title = "Scarecrow"
		url = "https://strootje.com/projs/scarecrow"

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1
[[menu.main]]
	name = "About"
	url = "/about/"
	weight = 2
[[menu.main]]
	name = "Contact"
	url = "/contact/"
	weight = 3
