languageCode = "en"

title = "scarecrow"
baseURL = "http://localhost/"
DefaultContentLanguage = "en"
paginate = 6

[languages.en]
languageName = "English"
weight = 1

# [languages.tp]
# languageName = "Toki Pona"
# weight = 99

[params]
	author = "Scarecrow"
	logo = "images/scarecrow.jpg"
	font = "Poppins"
	showRelated = true
	showHeaders = false
	[params.about]
		title = "Bas Stroosnijder"
		tagline = "FOSS since 1991"
		[params.about.logo]
			src = "images/scarecrow.jpg"
	[params.widgets]
		sidebar = [ "powered-by" ]
	[[params.poweredBy]]
		title = "Hugo"
		version = "0.51.0"
		url = "https://gohugo.io"
	[[params.poweredBy]]
		title = "Scarecrow"
		version = "0.1.0"
		url = "https://strootje.com/projs/scarecrow"

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1
[[menu.main]]
	name = "About"
	url = "/about/"
	weight = 2
[[menu.main]]
	name = "Contact"
	url = "/contact/"
	weight = 3
