languageCode = "en"

title = "scarecrow"
baseURL = "http://localhost:1313/"
DefaultContentLanguage = "en"
paginate = 6

enableEmoji = true
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsOptions = "linenos=true"

[languages.en]
	languageName = "English"
	contentDir = "content/en"
	weight = 1

[params]
	[params.options]
		showRelated = true
		font = "Poppins"
	[params.author]
		name = "Someone Awesome"
		tagline = "asdasd kjashdlkjad"
		logo = "images/scarecrow.jpg"
	[params.menu.social]
		target = "blank"

[[menu.main]]
	name = "About"
	weight = 100
	title = "about"
	url = "/about"

[[menu.social]]
	name = "LinkedIn"
	weight = 100
	title = "linkedin"
	url = "https://www.linkedin.com/in/<insert-name-here>"
	pre = "fab fa-linkedin-in"
[[menu.social]]
	name = "Instagram"
	weight = 200
	title = "instagram"
	url = "https://instagram.com/<insert-name-here>"
	pre = "fab fa-instagram"
[[menu.social]]
	name = "Github"
	weight = 300
	title = "github"
	url = "https://github.com/<insert-name-here>"
	pre = "fab fa-github-alt"
[[menu.social]]
	name = "Stackoverflow"
	weight = 400
	title = "stackoverflow"
	url = "https://stackoverflow.com/users/<insert-id-here>/<insert-name-here>"
	pre = "fab fa-stack-overflow"
[[menu.social]]
	name = "RSS"
	weight = 900
	title = "rss"
	url = "/posts/index.xml"
	pre = "fas fa-rss"
